### ISSUE TITLE
add whats wrong with essential 

### ISSUE THREAD

**Issue by kittenvr** [blryface/notessential#40] opened 2024-08-14 08:38 UTC
a page listing whats wrong with essential

**Comment by Nitrrine** [comment] 2024-08-14 08:42
Duplicate of #12

**Closed by Nitrrine** 2024-08-14 08:42 UTC
Labels: duplicate

**Comment by kittenvr** [comment] 2024-08-14 09:33
when will this be complete?

**Comment by KTrain5169** [comment] 2024-08-14 09:44
We are trying to get it done, however currently it breaks the website for some reason and we still have no idea why

**Comment by KTrain5169** [comment] 2024-08-14 09:45
also this should be closed as not planned but whatever
